apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:cluster-autoscaler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/part-of: travel-planner-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system
