CREATE TABLE community_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT uq_community_tag_name UNIQUE (name),
    CONSTRAINT ck_community_tag_name CHECK (btrim(name) <> '')
);
