apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: travel-planner-monitoring
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: travel-planner-monitoring
