logging:
  file:
    name: ${LOGGING_FILE_NAME:/var/log/travel-planner/travel-planner.log}
  structured:
    format:
      file: ecs
    ecs:
      service:
        environment: prod
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 20MB
      max-history: 7
      total-size-cap: 500MB

app:
  logging:
    error-frame-limit: 5
  auth:
    refresh-token:
      cookie-secure: ${REFRESH_TOKEN_COOKIE_SECURE:true}
    oauth:
      state-cookie-secure: true
  security:
    jwt:
      secret: ${JWT_SECRET}
