apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend
  - ../../../base/monitoring
patches:
  - path: backend-configmap.patch.yaml
  - path: backend-image.patch.yaml
